### ISSUE TITLE
Binary deb "package is of bad quality"

### ISSUE THREAD

**Issue by jiawen** [facebook/PathPicker#168] opened 2015-06-24 16:02 UTC
I just tried installing fpp 0.6.0 from the binary deb on the main GitHub page (https://github.com/facebook/PathPicker/releases/download/0.6.0/fpp.deb) on Ubuntu 14.04 LTS and in Ubuntu Software Center, it complains that "The package is of bad quality." The warning says:

The package is of bad quality

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /usr/local/google/home/jiawen/Downloads/fpp.deb:
mismatching contents of index files: 16:10 ./usr/share/doc/ ./ at /usr/share/lintian/collection/scripts line 37.
warning: collect info scripts about package pathpicker failed
warning: skipping check of binary package pathpicker
mismatching contents of index files: 16:10 ./usr/share/doc/ ./ at /usr/share/lintian/collection/md5sums line 52.
warning: collect info md5sums about package pathpicker failed
warning: skipping check of binary package pathpicker
mismatching contents of index files: 16:10 ./usr/share/doc/ ./ at /usr/share/lintian/collection/file-info line 67.
warning: collect info file-info about package pathpicker failed
warning: skipping check of binary package pathpicker

This is mildly scary and as a user, I wouldn't install it.

**Comment by pcottle** [comment] 2015-06-24 16:21
Yeah, this is an unfortunate issue with creating the packages on Mac systems (whereas debian ones don't produce packages that have these errors).

This is a dupe of #162, but I just realized that you can edit the file attachments for a given release, so I could update this ASAP. @jiawen or @eox-cs1 oe @pallavagarwal07 -- could any of you run the debian packager on your system and upload the package somewhere for the 0.6.1 release? I could then download it and replace the faulty one

**Comment by pallavagarwal07** [comment] 2015-06-24 20:30
Here it is:
https://drive.google.com/file/d/0B6jsnt965Zwrc05UYnFEVHVhQTQ/view?usp=sharing

**Comment by pcottle** [comment] 2015-06-24 22:45
Alright updated the release, new package is here:
https://github.com/facebook/PathPicker/releases/tag/0.6.1

Thanks @pallavagarwal07 for the quick fix! closing this out for now

**Closed by pcottle** 2015-06-24 22:45 UTC
Labels: awaiting-reply

**Comment by jiawen** [comment] 2015-07-09 21:44
Sorry for the delay, this fell off my radar. The 0.6.1 .deb works great on Ubuntu 14.04 and installs without any warnings. Thanks!
