### ISSUE TITLE
Not able to parse files at top level for `git grep "string" | fpp`

### ISSUE THREAD

**Issue by prat0318** [facebook/PathPicker#39] opened 2015-05-08 03:57 UTC
Other than `Dockerfile` (#7), it is also not able to parse `README.md` or any file present at top level.

Command given: $ `git grep "gitator" | fpp`

![screen shot 2015-05-07 at 10 53 22 pm](https://cloud.githubusercontent.com/assets/1528697/7530340/1a71c4cc-f50c-11e4-85d8-0f9919d8e85f.png)

**Comment by pedrox** [comment] 2015-05-10 13:41
Please, close this as a duplicate of #50.

**Closed** 2015-05-11 19:15 UTC
