### ISSUE TITLE
Doesn't handle filename with multiple periods and/or hyphen

### ISSUE THREAD

**Issue by raine** [facebook/PathPicker#50] opened 2015-05-08 08:03 UTC
From git status output:

![screenshot 2015-05-08 11 02 16](https://cloud.githubusercontent.com/assets/11027/7532628/c576d398-f571-11e4-865e-7d0ad0670250.png)

**Comment by imod** [comment] 2015-05-08 11:29
directories with periods are also not recognized properly

**Comment by sandyarmstrong** [comment] 2015-05-08 15:50
Duplicate of https://github.com/facebook/PathPicker/issues/18, which needs to be reopened.

**Closed** 2015-05-08 17:05 UTC

**Comment by sandyarmstrong** [comment] 2015-05-08 17:22
:100: Thanks!
