### ISSUE TITLE
Incorrect matching on files with multiple dots

### ISSUE THREAD

**Issue by sandyarmstrong** [facebook/PathPicker#18] opened 2015-05-07 19:29 UTC
If you have a file like "Company.Project.sln" or "archive.tar.gz", the highlighting and file name matching are incorrect. For example, `fpp` highlight and try to execute a command on "Project.sln" or "tar.gz".

**Comment by pcottle** [comment] 2015-05-08 01:28
Hey @sandyarmstrong 

I can't seem to reproduce this -- we definitely allow multiple periods in the filename:

![screen shot 2015-05-07 at 6 24 31 pm](https://cloud.githubusercontent.com/assets/1135007/7529008/70b22492-f4e6-11e4-8165-be87dc68bf71.png)
![screen shot 2015-05-07 at 6 24 39 pm](https://cloud.githubusercontent.com/assets/1135007/7529007/70b0b1b6-f4e6-11e4-87d3-cebc09d42098.png)

Can you perhaps provide some example input or a solid repro?

Note that we have separate regex for files that dont have a directory prepended to them (aka stuff like `echo.py`):
https://github.com/facebook/PathPicker/blob/master/src/parse.py#L30

but we have to be a lot more restrictive with that regex since we dont want to match JS code like:

```
data.object.some.field
```

(closing for now, reopen if you have the repro). a lot of this pain would go away if we simply checked if the file exists...

**Closed by pcottle** 2015-05-08 01:28 UTC

**Comment by sandyarmstrong** [comment] 2015-05-08 14:18
Your example only works because you provided an absolute path. It fails with relative paths. For example:

```bash
touch ~/banana.Project.sln
cd ~
echo banana.Project.sln | fpp
ls | fpp
```

Then you'll see the bad matching. I've tested with latest master.

**Comment by sandyarmstrong** [comment] 2015-05-08 17:23
Fixed in https://github.com/facebook/PathPicker/commit/37923571d8efc9020bf793ebb1e2fb1950c53ae2.
