### ISSUE TITLE
Cannot select folders or filenames without "."

### ISSUE THREAD

**Issue by joni2back** [facebook/PathPicker#70] opened 2015-05-09 13:52 UTC
I cant select a folder in the file list, and I could not find a parameter to do this..
![fpp](https://cloud.githubusercontent.com/assets/2049935/7550439/e4183c20-f638-11e4-8e53-7df1df7e236a.png)

**Comment by metavida** [comment] 2015-05-12 04:25
This seems like a duplicate of #7

**Comment by pcottle** [comment] 2015-05-12 20:42
PathPicker won't work with files, since implementing NERDTree-like functionality is an antigoal. But NERDTree is a great tool for that if you want to check it out!

Yeah lets move this into #83 which is tracking the filesystem validation task, which allows us to do all sorts of more aggressive matching (since we wont overmatch on text)

**Closed by pcottle** 2015-05-12 20:42 UTC
