### ISSUE TITLE
dotfiles are ignored

### ISSUE THREAD

**Issue by mellowcandle** [facebook/PathPicker#55] opened 2015-05-08 14:17 UTC
for instance if I have 
.gitignore
in my git status output. it can't be selected using PathPicker.

**Comment by metavida** [comment] 2015-05-08 21:04
I've got a WIP fix for this: https://github.com/metavida/PathPicker/tree/include_git_status_dotfiles

**Comment by pedrox** [comment] 2015-05-10 13:32
I believe dot files inside directory are not a problem.
So the issue is actualy about dot files and with not period in the current directory. Do you confirm? It seems that those are not detected by design since it's more likely that they are not paths in the input.

**Comment by pedrox** [comment] 2015-05-10 13:42
This is a duplicate of #7.

**Comment by metavida** [comment] 2015-05-11 20:19
Thanks for checking out this ticket @pedrox. First, I'd like to make a clarification. When I say "dotfile" I mean "any file that begins with a period"[[1]].

> I believe dot files inside directory are not a problem.

I confirmed that PathPicker does **not** recognize dotfiles within a directory by adding the following case to `test.py` on the latest master branch commit.

```py
{
    'input': 'tmp/.gitignore',
    'match': True,
    'file': 'tmp/.gitignore',
    'num': 0
}
```
```bash
$ git log -n1 | head -n1
commit 7b0bef202b9f4783197459e26fe658f404b99188
$ python src/test.py
...
======================================================================
FAIL: testFileMatch (__main__.TestParseFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/test.py", line 244, in testFileMatch
    self.checkFileResult(testCase)
  File "src/test.py", line 252, in checkFileResult
    testCase['input'])
AssertionError: Line "tmp/.gitignore" did not match any regex

----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=2, errors=1)
```

> This is a duplicate of #7.

To my reading, issue #7 is about detecting files with no extensions (e.g. `Makefile`). While this issue is similar, I would suggest that this ticket is *not* a duplicate of #7 because it's quite possible to have a dotfile with an extension (e.g. `.env.production` or `.hidden.txt`).

[1]:http://en.wikipedia.org/wiki/Dot-file

**Closed** 2015-05-11 21:57 UTC
